name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: luacheck
        uses: Jayrgo/luacheck-action@v1
